### ISSUE TITLE
Allow node manager and plugin reload at runtime

### ISSUE THREAD

**Issue by aevitas** [BosslandGmbH/BuddyWing#1]
Currently, when zoning, the NodeManager and various other engine related things are reloaded to re-align them with the game's engine.

When stopping the bot, zoning, and starting the bot again, the bot won't detect a zone change, and currently, the bot will need to be restarted in order to work again. We should allow users to reload the node manager et al. at runtime, especially since these engine misalignment issues can randomly occur as well.

On top of that, API should be provided to plugins to perform this action.

**Comment by LazyJedi** [comment]
I think pointers to internal game objects are not actual values after zoning.

**Comment by aevitas** [comment]
@LazyJedi That's correct, the game engine re-arranges various internals when you zone. We have code that adapts to this when zoning, but only when the bot's running.

**Comment by LazyJedi** [comment]
Why don't you run this code before each start?

**Comment by aevitas** [comment]
Implemented, will be in the next drop.

And @LazyJedi - I've also implemented your suggestion, the node manager will now automatically reload upon starting the bot, rather than just once on initialization.
