### ISSUE TITLE
Save Settings Button

### ISSUE THREAD

**Issue by LazyJedi** [BosslandGmbH/BuddyWing#10]
I need to be able to save the settings manually without any magic.
Settings must be saved to disk only when I click [Save Settings] button. No other way.
This will solve the problem with the loss of the settings after the crash.

**Comment by aevitas** [comment]
Good suggestion, we can definitely make this happen.

**Comment by aevitas** [comment]
Done - will be included in the next update.

**Comment by LazyJedi** [comment]
Save Settings button dosn't save window position.
1. move bot window
2. press Save Settings button
3. press Reload button
4. window moves to old position
