### ISSUE TITLE
remove harvesting level requirements

### ISSUE THREAD

**Issue by armyruss79** [BosslandGmbH/BuddyWing#18]
Game no longer requires us to harvest nodes at a specific skill level. You can have level skill you can harvest a level 550 node

**Comment by aevitas** [comment]
So we can harvest any node for a profession, as long as we have at least 1 profession skill level for the profession required?

**Comment by armyruss79** [comment]
Yes there is no longer a skill level requirement. The skill will continue to level to 550 but the game does not require a node level requirement. learn three gathering skills go straight to yavin4 and start harvesting at level 1 skill level. the nodes are 450+

**Comment by aevitas** [comment]
Thanks, we'll sneak this change in for tonight's update! If you could test it after tonight's release and let me know whether it's working that'd be great - I don't expect any huge problems to come from this change.
