### ISSUE TITLE
Add pause button and/or keybind

### ISSUE THREAD

**Issue by armyruss79** [BosslandGmbH/BuddyWing#19]
Requesting implementation of a simple pressing of a predefined button that puts the bott in a paused / neutral state so we can transition through dialogues and zoning in. This is to prevent bot crashes while in instances / raids / questing

**Comment by armyruss79** [comment]
Requdesting implementation of a simple pressing of a predefined button that puts the bott in a paused / neutral state so we can transition through dialogues and zoning in. This is to prevent bot crashes while in instances / raids / questing

**Comment by aevitas** [comment]
Implemented - will use the F9 key by default, and will be configurable later down the line. 

As an aside, F10 can now be used to stop/start the bot while in-game.
