### ISSUE TITLE
Issues with targeting in crowded zones

### ISSUE THREAD

**Issue by aevitas** [BosslandGmbH/BuddyWing#21]
Multiple users have reported the bot going "crazy" on targeting, and ending up targeting its own companion and AFK-ing out after a certain period of time.

This will need more info, but it's a rather big issue.

**Comment by aevitas** [comment]
Scheduled for the future, as there's currently not enough information to fix this.

**Comment by Wired203** [comment]
I have seen this happen as I sit and watch my bots.  Bot will have locked onto a target and be moving to it (mob, node) and the item disappears either someone killed the mob while you were traveling to it or the node got harvested.  Bot would just then stop where he was and stay until restarted or afk logout.  Personally haven't botted much lately but this is the behavior I saw when it occurred.

**Comment by aevitas** [comment]
We have some improvements coming up for this issue in the next update. Changing the milestone to the March one for now.

**Comment by aevitas** [comment]
This should be fixed as of the latest release.
