### ISSUE TITLE
Bug Discipline CanNotBeDetermined   Bodyguard

### ISSUE THREAD

**Issue by Wired203** [BosslandGmbH/BuddyWing#24]
[DefaultCombat] Level: 65
[DefaultCombat] Class: BountyHunter
[DefaultCombat] Advanced Class: Mercenary
[DefaultCombat] Discipline: CanNotBeDetermined

Should be Bodyguard

**Comment by Wired203** [comment]
Also noted were 
Commando -> Combat Medic
Sentinel -> Watchman

**Comment by aevitas** [comment]
This is an issue related to [BuddyWing.DefaultCombat](https://github.com/BosslandGmbH/BuddyWing.DefaultCombat/issues). Could you please raise the issue there? Thanks.

**Comment by Wired203** [comment]
Moved to Default Combat

**Comment by aevitas** [comment]
Thanks!
