### ISSUE TITLE
Improved API for Areaname and Zonename

### ISSUE THREAD

**Issue by CryoGenesisX** [BosslandGmbH/BuddyWing#31]
Currently we have only 3 apicalls to get the planetname.
This is done via TorMap.CurrentAreaName. I Would like to have this expanded to get the actual zone on this planet.
So we go from 3 to atleast 4 ApiCalls:
- CurrentAreaId
- CurrentAreaName
- CurrentAreaTerrainName
- CurrentZoneName

And add this to the MyLocation Dump function.
This would improve area detection and profile writing.

The ZoneName is just above and part of the minimap.

**Comment by aevitas** [comment]
The `TorMap` class could expose a couple more members than it currently does. I've added the following APIs to `TorMap`: 
- `TorMap.CurrentMapName` 
- `TorMap.MinimapTitle`
- `TorMap.IsSafeZone`
- `TorMap.IsMountAllowed`

CurrentMapName should be what you're after when you're looking for `CurrentZoneName`.
