### ISSUE TITLE
Ability to auto consume specific items from inventory?

### ISSUE THREAD

**Issue by pjmagee** [BosslandGmbH/BuddyWing#45]
Characters can gain extra experience from consuming experience boosts. It would be handy if the bot would consume an experience boost if it detects this buff is not currently active on the character and if it finds the experience boost in the inventory. 

Using a priority order of Minor > Major.

"Complimentary Experience Boost"
"Complimentary Major Experience Boost"
"Complimentary Minor Experience Boost"
"Major Experience Boost"
"Minor Experience Boost"
"Minor Class Mission Experience Boost"
"Minor Exploration Experience Boost"
"Major Exploration Experience Boost"

They are not stacking experience boosts. So only one may be active at a time. So priority is important. 

The minor experience boosts are also sometimes rewarded as you complete certain class quests. So it's usually something that would automatically be consumed if the Bot was in a stable state with a good profile that could improve levelling from 1 to 50+

**Comment by pjmagee** [comment]
I just realised this doesnt make a good issue and maybe a new repository for Plugins could be helpful?

Buddywing.Plugins github repo and maybe we can port over community contributed plugins into this repo.

**Comment by CryoGenesisX** [comment]
I added it to the testbuild of defaultcombat from Wired.
But I don't k ow if its in the live version now.
