### ISSUE TITLE
Basic Routine Determination

### ISSUE THREAD

**Issue by Logandros** [BosslandGmbH/BuddyWing#50]
As of 5.0 the bot can no longer assign a basic combat routine which is used on all characters prior to level 10. I believe that this is because Bioware now allows you to choose your discipline from level 1 where as previously it was not allowed until level 10 and you were immediately given a spell that we detected in DisciplineDetection.cs to determine the discipline.

My theory is that the bot in order for DisciplineDetection.cs to work correctly saw that there was no discipline attribute assigned to the character and would then as intended false to a basic combat routine. I think the bot now struggles because that attribute is now present at character creation so the bot expects to be able to find a discipline logic. Even if the user chooses a discipline at level 1, DisciplineDetection.cs would still fail because the spell logic does not exist (until level 10).

So we need a way to determine basic routines for characters that are < 10

**Comment by SirSik** [comment]
What about if the whole detection was wrapped with a 
`If (BuddyTor.Me.Level > 9)
{
*DisciplineDetection.cs code goes here*
}
`
Then add something at the end which is basically the same but detects buffs / resting spell.
For example:

`If (BuddyTor.Me.Level < 10
{
    If (HasAbility("Seethe") && advancedClass =AdvancedClass.Sorcerer
    { 
        discipline = *basic class code* 
    }
    If (HasAbility("Hatred") && advancedClass =AdvancedClass.Juggernaut
    { 
        discipline = *basic class code* 
    }
}
`

i've left a few blanks as i don't know what the values would be but you get the general idea

**Comment by Logandros** [comment]
Issue resolved in the next release.
