### ISSUE TITLE
System.Xml.XmlException: '<', hexidezimaler Wert 0x3C

### ISSUE THREAD

**Issue by derFalke** [BosslandGmbH/BuddyWing#65]
System.Xml.XmlException: '<', hexidezimaler Wert 0x3C, ist ein ungültiges Attributszeichen. Zeile 319, Position 55.

Code:
UserDialog Title="Note from derfalke" Message="<20" 

in a Messagebox the bot validate the "<" ?!?

**Comment by aevitas** [comment]
"<" is a special character in XML, so it'll need to be escaped. Iirc the escape for < is `&lt;`, can you see if that works?

**Comment by derFalke** [comment]
ahh ok so this can be closed ...

**Comment by aevitas** [comment]
Closed upon request
