### ISSUE TITLE
Repair and mail droid support

### ISSUE THREAD

**Issue by CryoGenesisX** [BosslandGmbH/BuddyWing#9]
Adding "Deploy Field Repair Droid" to the logic for repairing/vendoring.
Gives farmers more freedom to farm spots where we cant go to vendors.
Search for "Field Repair Droid". It has 3 types:
- Basic Field Repair Droid
- Improved Field Repair Droid
- Advanced Field Repair Droid

Adding "Deploy Field Mail Droid" for sending specific types of items to mules.
Currently, the bot lacks mail support.
Search for "Field Mail Droid".

**Comment by aevitas** [comment]
We currently don't support mailing in the bot, but using the droids for vendoring should be doable, as a start.

**Comment by aevitas** [comment]
@CryoGenesisX Are these castable spells or items?

**Comment by CryoGenesisX** [comment]
Castable spells

**Comment by aevitas** [comment]
Right, in that case it'd look something along the lines of:

```
    private static readonly string[] _droids =
    {
        "Basic Field Repair Droid", "Improved Field Repair Droid",
        "Advanced Field Repair Droid"
    };

    private static Composite CreateRepairDroidBehavior()
    {
        return new PrioritySelector(
            new Decorator(ret => { return _droids.Any(d => AbilityManager.CanCast(d, BuddyTor.Me)); },
                new Sequence(new Action(ret =>
                {
                    var droid = _droids.FirstOrDefault(d => AbilityManager.CanCast(d, BuddyTor.Me));

                    if (!string.IsNullOrEmpty(droid))
                        AbilityManager.Cast(droid, BuddyTor.Me);
                    else
                    {
                        _log.Warn("Previous tick indicated repair droid could be used, but we couldn't cast any?");
                    }
                }),
                    new Sleep(TimeSpan.FromSeconds(3)))));
    }
```

Subsequent vendor selection should then select the droid as the nearest repair vendor and use it to repair and vendor, theoretically. This'll need some extensive testing before we can ship it though.

**Comment by CryoGenesisX** [comment]
We still have to implement the vendorlocation in the profiles, where its gonna summon the droid?
Or is it gonna summon the droid in the field, the second it reaches it 'full-bag' value?

Problem back in the day, JoesCombat had this implemented, but it took minutes to detect the droid.
Still happy to test this out.

**Comment by aevitas** [comment]
As it stands, the idea is to have it summon the droid on the spot as soon as it runs the vendor logic. The bot would determine it needs to vendor, summon the droids, and clear the POI. That way, it'll re-select the vendor POI and the droid will be the nearest NPC that can vendor. That should, in theory, mean there is virtually no downtime in selecting the droid as there was before.

Let me know if you have any suggestions for a better solution, otherwise I can work on implementing this in the next build.

**Comment by CryoGenesisX** [comment]
If the summoning, detection and vendoring doesnt take long, ie under 1m, i dont see problems.

Problem could be the following:
- Droid is summoned on top of fresh downed NPCs with low respawntime, we could get attacked during vendoring if it takes too long.
- Vendoring is done in patrolpaths of Elites/Bosses
- User has no input over the vendoring with a droid (safe spots)
- Profiles dont load without a vendor

**Comment by aevitas** [comment]
We're currently testing the above solution.

**Comment by aevitas** [comment]
We're adding some more logging to this, but the current solution will need further testing and feedback. Marking this ticket as closed for now, until we can gather more feedback on it.

As an aside, the skill name is Deploy Field Repair Droid.
